# Generated by Django 5.2.4 on 2025-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_customuser_city_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_complete',
            field=models.BooleanField(default=False, verbose_name='First login complete'),
        ),
    ]
